import type {
  CropRecommendation,
  CropTier,
  Financials,
  PestDiseaseRisk,
  RadarMetrics,
  RegionKey,
  SeasonKey,
  TimelineCategory,
  TimelineStage,
  WaterStagePoint,
} from "./types";

let counter = 0;

function makeCrop(
  tier: CropTier,
  crop: string,
  tag: string,
  reason: string,
  advisorTip: string,
  sowingWindow: string,
  duration: number,
  companion: string,
  expectedYield: string,
  marketDemand: string,
  waterRequirement: string,
  radarMetrics: RadarMetrics,
  financials: Financials,
  waterStageCurve: WaterStagePoint[],
  pestAndDiseaseRisk: PestDiseaseRisk,
  growthTimeline: TimelineStage[],
): CropRecommendation {
  counter += 1;
  return {
    id: `fb-${counter}`,
    tier,
    crop,
    tag,
    reason,
    advisorTip,
    sowingWindow,
    duration,
    companion,
    expectedYield,
    marketDemand,
    waterRequirement,
    radarMetrics,
    financials,
    waterStageCurve,
    pestAndDiseaseRisk,
    growthTimeline,
  };
}

function stages(
  specs: [string, number, TimelineCategory, string[], string][],
): TimelineStage[] {
  return specs.map(([name, days, category, tasks, tip], i) => ({
    id: `st-${i}`,
    name,
    days,
    category,
    tasks,
    expertTip: tip,
  }));
}

function wc(...points: [string, number][]): WaterStagePoint[] {
  return points.map(([stage, waterNeed]) => ({ stage, waterNeed }));
}

export const FALLBACK_CROPS: Record<
  RegionKey,
  Record<SeasonKey, CropRecommendation[]>
> = {
  heavy_rainfall: {
    kharif: [
      makeCrop(
        "primary",
        "Indrayani Paddy (Jarhan)",
        "Primary Recommended Crop",
        "Indrayani is a fragrant, fine-grained indigenous paddy that thrives in the 2500mm+ monsoon downpours of Igatpuri and Trimbakeshwar. The acidic red/laterite slopes drain well, preventing waterlogging, while the cool misty microclimate extends the grain-filling window for superior aroma.",
        "Puddle the field 2 weeks before transplanting and apply 50:25:25 kg N:P:K per acre. Split nitrogen — half at tillering and half at panicle initiation — and top-dress with 12kg zinc sulphate per acre to correct laterite zinc deficiency.",
        "Mid-June to mid-July (nursery first week of June)",
        130,
        "Nagli (finger millet) on bunds; fish in paddy trenches",
        "4.5–5.5 t/ha (1.8–2.2 t/acre) of paddy",
        "Premium fine rice fetches ₹2,800–3,400 per quintal at Igatpuri and Nashik wholesale; strong Kolhapur–Pune and local temple-town demand for the aromatic grain.",
        "High: relies on assured monsoon (2200–2600mm), plus 4–5 protective irrigations during a dry spell. No borewell dependency.",
        {
          yieldPotential: 82,
          marketValue: 85,
          waterEfficiency: 55,
          soilCompatibility: 85,
          climateResilience: 78,
        },
        { inputCostPerAcre: 12000, grossRevenuePerAcre: 41000, netProfitPerAcre: 29000 },
        wc(
          ["Nursery/Sowing", 60],
          ["Vegetative", 340],
          ["Flowering/Panicle", 420],
          ["Maturity/Harvest", 120],
        ),
        {
          primaryPests: ["Yellow stem borer", "Brown planthopper", "Rice hispa"],
          primaryDiseases: ["Rice blast", "Brown spot", "Bacterial leaf blight"],
          riskLevel: "medium",
          ipmAdvice: [
            "Install pheromone traps at 12/ha for stem borer from 30 days after transplanting.",
            "Do not over-dose nitrogen — lush canopies invite blast; keep field flooded intermittently (AWD).",
            "Apply Pseudomonas fluorescens 500g/acre in nursery to suppress soil-borne disease.",
          ],
          symptoms: [
            "Whiteheads and dead hearts in tillers",
            "Elliptical grey-green lesions with brown border on leaves",
            "Yellowing leaf tips curling downward (hopper burn)",
          ],
        },
        stages([
          [
            "Nursery & Sowing",
            28,
            "sowing",
            [
              "Raise nursery on raised beds; sow 12kg seed per acre",
              "Maintain 3–4cm standing water; drench with 4kg carbendazim",
              "Prepare main field: puddle twice and level",
            ],
            "Use dapog or wet-bed nursery to save seed and transplant 20–25 day-old seedlings at 2 seedlings per hill.",
          ],
          [
            "Transplanting & Tillering",
            45,
            "irrigation",
            [
              "Transplant at 20×15cm spacing",
              "Apply 25kg N as basal; irrigate at 3-day intervals",
              "Undertake gap filling by 10th day",
            ],
            "Keep a 4–5cm water depth during tillering and drain completely at panicle initiation to trigger tillering.",
          ],
          [
            "Panicle & Grain Filling",
            40,
            "fertilization",
            [
              "Top-dress 25kg N and 20kg K at panicle initiation",
              "Spray 0.2% zinc sulphate with sticker",
              "Monitor stem borer; avoid water stress during flowering",
            ],
            "A 10-day mid-season drainage (AWD) at panicle initiation hardens the crop and curbs leaf blast.",
          ],
          [
            "Maturity & Harvest",
            17,
            "harvest",
            [
              "Harvest at 22–24% moisture; thresh and sun-dry to 14%",
              "Grade by aroma and grain length for premium lot",
              "Store in clean gunny or hermetic bags",
            ],
            "Do not delay harvest — over-ripe panicles shatter and lose the prized aroma.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Nagli / Finger Millet (Ragi)",
        "Climate-Resilient Staple",
        "Nagli is the traditional hardy grain of the Ghat slopes, perfectly suited to the rainfed acidic laterite terraces of Igatpuri. It shrugs off erratic monsoon breaks, matures fast, and stores well — an ideal risk buffer for the heavy-rain belt.",
        "Sow 8–10kg seed/acre on ridges after the second good shower. Give a single hoeing at 25 days and top-dress 25kg N at 40 days. Harvest before excess moisture rots the earheads.",
        "Third week of June to first week of July",
        95,
        "Black gram in rows; pigeon pea on field border",
        "1.2–1.5 t/acre of grain",
        "Local Ghat market demand is consistent; growing health-food interest in Nashik city and Mumbai keeps prices stable around ₹2,200–2,800 per quintal.",
        "Low–medium: rainfed; needs only 2–3 life-saving irrigations in drought-stressed patches.",
        {
          yieldPotential: 62,
          marketValue: 62,
          waterEfficiency: 90,
          soilCompatibility: 82,
          climateResilience: 88,
        },
        { inputCostPerAcre: 6000, grossRevenuePerAcre: 18000, netProfitPerAcre: 12000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 160],
          ["Flowering/Panicle", 180],
          ["Maturity/Harvest", 60],
        ),
        {
          primaryPests: ["Pink stem borer", "Armyworm", "Root grub"],
          primaryDiseases: ["Blast", "Downy mildew", "Foot rot"],
          riskLevel: "low",
          ipmAdvice: [
            "Deep summer ploughing exposes root grub pupae.",
            "Remove and burn blast-affected tillers early.",
            "Intercrop with pulses to break pest cycles.",
          ],
          symptoms: [
            "Grey centres with purple margins on leaves (blast)",
            "White powdery growth on lower leaves",
            "Dead hearts during vegetative stage",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Line sow 8–10kg seed/acre on ridges at 30cm spacing",
              "Apply 10:20:20 basal NPK",
              "Weed manually at 20–25 days",
            ],
            "Soak seed in 2% salt solution to discard chaffy, blighted grains before sowing.",
          ],
          [
            "Vegetative Growth",
            40,
            "irrigation",
            [
              "Irrigate at 10-day intervals if dry spell exceeds 15 days",
              "Top-dress 25kg N at 40 days",
              "Earth up rows to aid tillering",
            ],
            "Ragi tolerates temporary drought; avoid over-watering which invites blast.",
          ],
          [
            "Flowering & Grain Fill",
            25,
            "fertilization",
            [
              "Spray 0.5% potassium nitrate at flowering",
              "Control armyworm before ear emergence",
              "Skim sow a second row if stand is poor",
            ],
            "Grain set is best at 24–28°C; avoid severe moisture stress at flowering.",
          ],
          [
            "Maturity & Harvest",
            18,
            "harvest",
            [
              "Harvest when 80% earheads mature",
              "Dry earheads thoroughly before threshing",
              "Winnow and store with neem-leaf protection",
            ],
            "Nagli stores for years if moisture is below 10% — a genuine famine insurance crop.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Black Gram / Urad (var. TAU-1)",
        "Short-Duration Pulse",
        "TAU-1 black gram matures in barely 70–80 days, fitting neatly into the tail of the heavy monsoon in Igatpuri's terraced fields. Its nitrogen fixation rebuilds the leached laterite soil while delivering a high-priced pulse at a time of year when the market is short.",
        "Sow 8kg seed/acre after paddy harvest or as a paddy–urad sequence. Seed-treat with Rhizobium to double nodulation. Harvest at 90% pod maturity — over-drying splits the seed coat and drops the grade.",
        "Late July to mid-August (paddy fallow fit)",
        78,
        "Paddy (sequence); fodder maize on bunds",
        "400–500 kg/acre of dal-grade grain",
        "Urad is in perennial short supply at Nashik and Lasalgaon; dal mills pay ₹7,000–9,000 per quintal for clean black gram.",
        "Low: benefits from receding monsoon moisture; 1–2 supplemental irrigations only if dry spell crosses 20 days.",
        {
          yieldPotential: 55,
          marketValue: 82,
          waterEfficiency: 85,
          soilCompatibility: 76,
          climateResilience: 82,
        },
        { inputCostPerAcre: 5200, grossRevenuePerAcre: 20000, netProfitPerAcre: 14800 },
        wc(
          ["Nursery/Sowing", 35],
          ["Vegetative", 130],
          ["Flowering/Panicle", 120],
          ["Maturity/Harvest", 40],
        ),
        {
          primaryPests: ["Gram pod borer", "Sucking pest complex (jassid, whitefly)", "Aphid"],
          primaryDiseases: ["Yellow mosaic virus", "Cercospora leaf spot", "Powdery mildew"],
          riskLevel: "medium",
          ipmAdvice: [
            "Use YMV-resistant TAU-1 to dodge the biggest urad killer.",
            "Yellow sticky traps at 10/ha to monitor whitefly vectors.",
            "Spray neem oil 2% at flowering against pod borers.",
          ],
          symptoms: [
            "Yellow mottling and crinkling of young leaves (YMV)",
            "Brown circular spots with grey centre on leaves",
            "Bores on pods with frass visible at entry hole",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Line sow 8kg/acre at 30×10cm",
              "Inoculate seed with Rhizobium culture",
              "Apply 10:20:20 basal at sowing",
            ],
            "Sow shallow (3–4cm) into residual moisture — deep sowing delays emergence.",
          ],
          [
            "Vegetative Growth",
            30,
            "irrigation",
            [
              "Weed and hoe at 20 days",
              "Irrigate if dry spell exceeds 20 days",
              "Top-dress 10kg N at branching",
            ],
            "Keep the crop weed-free in the first month; urad competes poorly with weeds.",
          ],
          [
            "Flowering & Pod Set",
            25,
            "fertilization",
            [
              "Spray 0.2% boron at flower initiation",
              "Monitor pod borer weekly with pheromone traps",
              "Avoid excessive nitrogen — invites succulent growth and YMV vector",
            ],
            "Urad is highly sensitive to waterlogging at flowering; ensure field drains quickly.",
          ],
          [
            "Maturity & Harvest",
            13,
            "harvest",
            [
              "Harvest at 85–90% pod maturity",
              "Sun-dry on clean floor; thresh gently",
              "Grade and market as dal-grade urad",
            ],
            "Dry pods to 9% moisture before storage to keep the prized shiny black coat intact.",
          ],
        ]),
      ),
    ],
    rabi: [
      makeCrop(
        "primary",
        "Gram / Chana (var. Digvijay)",
        "Primary Recommended Crop",
        "Gram fits perfectly into the post-monsoon residual moisture of Igatpuri's red laterite terraces. Digvijay resists wilt and ascochyta blight, matures in about 100 days, and pockets the strong winter pulse premium that Nashik's dal trade pays.",
        "Sow 25kg seed/acre at 30×10cm immediately after the last October rain to trap soil moisture. Seed-treat with Trichoderma and carbendazim against wilt. A single pre-flowering irrigation doubles pod set.",
        "Mid-October to mid-November",
        105,
        "Mustard (border rows); coriander intercrop",
        "750–900 kg/acre of clean grain",
        "Chana prices at Lasalgaon APMC hover ₹5,000–6,500/quintal; ample local milling demand.",
        "Low–medium: grows on residual monsoon moisture; 1–2 irrigations (pre-flowering and pod filling) lift yield sharply.",
        {
          yieldPotential: 68,
          marketValue: 86,
          waterEfficiency: 76,
          soilCompatibility: 78,
          climateResilience: 82,
        },
        { inputCostPerAcre: 7000, grossRevenuePerAcre: 29000, netProfitPerAcre: 22000 },
        wc(
          ["Nursery/Sowing", 50],
          ["Vegetative", 220],
          ["Flowering/Panicle", 260],
          ["Maturity/Harvest", 80],
        ),
        {
          primaryPests: ["Gram pod borer", "Semi-looper", "Aphid"],
          primaryDiseases: ["Wilt (Fusarium)", "Ascochyta blight", "Rust"],
          riskLevel: "medium",
          ipmAdvice: [
            "Seed treatment with Trichoderma viride 5g/kg suppresses wilt at source.",
            "Pheromone traps (10/ha) from flower initiation for pod borer.",
            "Do not sow into standing water — waterlogging triggers collar rot.",
          ],
          symptoms: [
            "Sudden wilting and drooping of plants at flowering",
            "Circular grey-brown spots with dark margin on leaves/pods",
            "Small round bores on pods with caterpillar frass",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 25kg seed/acre at 30×10cm depth 8cm",
              "Apply 10:20:20 NPK + seed inoculate with Rhizobium",
              "Irrigate lightly immediately after sowing if soil is dry",
            ],
            "Sow gram on residual moisture before the field fully dries out — delayed sowing cuts yield by a third.",
          ],
          [
            "Vegetative Growth",
            45,
            "irrigation",
            [
              "Hoe and weed at 25 days",
              "Pre-flowering irrigation at 50 days",
              "Top-dress 20kg N at branching",
            ],
            "The pre-flowering irrigation is the single highest-return water applied to gram.",
          ],
          [
            "Flowering & Pod Filling",
            40,
            "fertilization",
            [
              "Spray 0.2% boron at flowering",
              "Second irrigation at full pod filling",
              "Monitor pod borer weekly",
            ],
            "Gram flowers over 4–6 weeks; extend flowering with a mild moisture supply to raise pod load.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Harvest when 80% pods turn yellow",
              "Stack, sun-dry and thresh",
              "Clean and bag for APMC",
            ],
            "Dry chana to 10% moisture; greenish seeds attract moisture and discount at auction.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Garden Pea (var. Arkel)",
        "High-Value Cool-Season Vegetable",
        "The cool misty winter of the Ghat belt is ideal for early Arkel peas, which command a strong off-season premium in Mumbai and Pune before North Indian supplies arrive. Well-drained laterite keeps roots healthy through the damp winter.",
        "Sow 12–15kg seed/acre at 30×15cm with 8–10cm deep trenches for irrigation. Support with stakes and irrigate every 7–8 days in the absence of winter rain.",
        "October to mid-November",
        100,
        "Radish or carrot intercrop between rows",
        "4–5 t/acre of green pods",
        "December peas at Nashik–Mumbai wholesale hit ₹60–80/kg; strong festive demand.",
        "Medium: 8–10 irrigations through winter; no summer dependency.",
        {
          yieldPotential: 76,
          marketValue: 76,
          waterEfficiency: 66,
          soilCompatibility: 72,
          climateResilience: 68,
        },
        { inputCostPerAcre: 15000, grossRevenuePerAcre: 46000, netProfitPerAcre: 31000 },
        wc(
          ["Nursery/Sowing", 50],
          ["Vegetative", 180],
          ["Flowering/Panicle", 220],
          ["Maturity/Harvest", 110],
        ),
        {
          primaryPests: ["Pea pod borer", "Semi-looper", "Aphid"],
          primaryDiseases: ["Powdery mildew", "Root rot", "Downy mildew"],
          riskLevel: "medium",
          ipmAdvice: [
            "Spray wettable sulphur 0.2% at first mildew spot.",
            "Hand-pick and destroy early pod borer infested pods.",
            "Avoid dense sowing — airflow suppresses mildew.",
          ],
          symptoms: [
            "White powdery coating on leaves and pods",
            "Bores and frass on young pods",
            "Yellowing and stunting from root rot",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 12–15kg seed/acre at 30×15cm",
              "Apply 20:40:40 basal NPK",
              "Provide 8–10cm deep irrigation furrows",
            ],
            "Treat seed with PSB culture — peas fix their own nitrogen with good rhizobia.",
          ],
          [
            "Vegetative Growth",
            40,
            "irrigation",
            [
              "Irrigate every 7–8 days",
              "Hoe and earth up at 30 days",
              "Install stakes before vines sprawl",
            ],
            "Keep canopy open; dense vines invite powdery mildew in the humid Ghat winter.",
          ],
          [
            "Flowering & Pod Set",
            38,
            "fertilization",
            [
              "Top-dress 15kg N at flowering",
              "Spray 0.5% potassium nitrate at pod set",
              "Weekly pod borer monitoring",
            ],
            "Pick every alternate day once pods firm — regular picking extends the crop 2–3 weeks.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Harvest at 90–100 days with firm green pods",
              "Grade pods by size; refrigerate immediately",
              "Dispatch overnight to Mumbai wholesale",
            ],
            "Cool pods within 4 hours of picking to hold the crisp sweetness premium.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Potato (var. Kufri Badshah)",
        "Off-Season Slope Crop",
        "The cooler Igatpuri slopes produce early potatoes that hit the market before the main Deccan crop. Kufri Badshah yields well in the mild Ghat winter on well-drained red soil, capturing a lucrative early-season window.",
        "Plant 900–1000kg seed tubers/acre in ridges at 60×20cm. Apply 60:40:60 NPK, half at planting and half at earthing-up. Stop irrigation 2 weeks before harvest to firm the skin.",
        "Late November to mid-December",
        95,
        "Spinach or coriander on ridges; onion sequence",
        "9–11 t/acre of marketable tubers",
        "Early potatoes at Nashik market bring ₹20–28/kg; demand peaks before the Maharashtra main crop.",
        "Medium: 7–9 irrigations; sensitive to both waterlogging and drought.",
        {
          yieldPotential: 80,
          marketValue: 80,
          waterEfficiency: 52,
          soilCompatibility: 70,
          climateResilience: 65,
        },
        { inputCostPerAcre: 30000, grossRevenuePerAcre: 66000, netProfitPerAcre: 36000 },
        wc(
          ["Nursery/Sowing", 60],
          ["Vegetative", 240],
          ["Flowering/Panicle", 320],
          ["Maturity/Harvest", 90],
        ),
        {
          primaryPests: ["Aphid (PVY vector)", "White grub", "Cutworm"],
          primaryDiseases: ["Late blight", "Early blight", "Scab"],
          riskLevel: "high",
          ipmAdvice: [
            "Spray Mancozeb 75WP or prophylactic Blitox at 2-week intervals once canopy closes.",
            "Rogue and destroy virus-diseased plants early.",
            "Use certified disease-free seed; never carry-over field tubers.",
          ],
          symptoms: [
            "Water-soaked dark lesions on leaves spreading fast (late blight)",
            "Brown concentric ring spots (early blight)",
            "Mosaic, leaf curling from virus",
          ],
        },
        stages([
          [
            "Planting",
            10,
            "sowing",
            [
              "Plant 900–1000kg seed/acre at 60×20cm",
              "Apply basal half of NPK in furrows",
              "Irrigate lightly immediately after planting",
            ],
            "Use only certified Kufri Badshah seed — PVY in saved tubers silently cuts yield.",
          ],
          [
            "Vegetative Growth",
            40,
            "irrigation",
            [
              "Irrigate every 6–7 days; avoid over-saturation",
              "Earthing-up + half N at 35 days",
              "Start late-blight spray schedule",
            ],
            "Moist Ghat winters favour late blight; stay disciplined on the spray calendar.",
          ],
          [
            "Flowering & Tuber Bulking",
            35,
            "fertilization",
            [
              "Potassium top-dress 25kg at flowering for bulking",
              "Continue blight sprays at 14-day intervals",
              "Stop irrigation 15 days before harvest",
            ],
            "Tuber bulking needs steady moisture — a dry week at this stage halves grade-A tubers.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Harvest 2–3 weeks after haulm dry-off",
              "Cure tubers 10 days in shade",
              "Grade and dispatch to early market",
            ],
            "Never store bruised tubers; they rot fast and drag the whole lot's price.",
          ],
        ]),
      ),
    ],
    summer: [
      makeCrop(
        "primary",
        "Summer Groundnut (var. TAG-24)",
        "Primary Recommended Crop",
        "TAG-24's short duration and high oil content suit the mild pre-monsoon heat of the Ghat belt on well-drained red laterite. Groundnut rebuilds soil organic matter, and with protective irrigation delivers a lucrative summer pulse-oil crop before the rains return.",
        "Sow 60–70kg kernel seed/acre at 30×10cm after soil testing (pH 6.0–6.5). Gypsum 125kg/acre at flowering is mandatory for pod filling. Stop watering 20 days before harvest for clean curing.",
        "February to mid-March",
        110,
        "Onion sequence; pigeon pea as border guard",
        "1.0–1.2 t/acre of dry pods",
        "Groundnut at Lasalgaon and Dindori fetches ₹4,500–5,500/quintal for milling-grade bold kernels.",
        "Medium: 8–10 protective irrigations; the crop completes before monsoon onset.",
        {
          yieldPotential: 70,
          marketValue: 80,
          waterEfficiency: 56,
          soilCompatibility: 76,
          climateResilience: 72,
        },
        { inputCostPerAcre: 14000, grossRevenuePerAcre: 44000, netProfitPerAcre: 30000 },
        wc(
          ["Nursery/Sowing", 60],
          ["Vegetative", 220],
          ["Flowering/Panicle", 280],
          ["Maturity/Harvest", 90],
        ),
        {
          primaryPests: ["Tobacco caterpillar (Spodoptera)", "Leaf miner", "White grub"],
          primaryDiseases: ["Tikka leaf spot", "Rust", "Collar rot"],
          riskLevel: "medium",
          ipmAdvice: [
            "Spray chlorothalonil or mancozeb at 15-day intervals from 45 days against tikka.",
            "Drench collar region with carbendazim at first wilt signs.",
            "Deep ploughing before sowing kills white grub pupae.",
          ],
          symptoms: [
            "Small brown circular spots with yellow halo on leaves",
            "Orange-brown pustules on under-surface (rust)",
            "Sudden collapse of seedlings near soil line",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 60–70kg seed/acre at 30×10cm",
              "Apply 10:25:25 NPK basal",
              "Light irrigation immediately to sprout",
            ],
            "Kernel treatment with thiram before sowing keeps collar rot away in warm summer soil.",
          ],
          [
            "Vegetative Growth",
            40,
            "irrigation",
            [
              "Irrigate at 8-day intervals",
              "Two hoeings for aeration",
              "Start tikka spray schedule at 45 days",
            ],
            "Peanuts peg into soil — light hoeing at 40 days helps the pegs penetrate.",
          ],
          [
            "Flowering & Pegging",
            40,
            "fertilization",
            [
              "Apply gypsum 125kg/acre at flower initiation",
              "Spray 0.3% zinc sulphate twice",
              "Monitor Spodoptera weekly",
            ],
            "Gypsum supplies calcium to developing pods — the highest-ROI input in groundnut.",
          ],
          [
            "Maturity & Harvest",
            18,
            "harvest",
            [
              "Harvest at 75% mature pods (dark testa)",
              "Sun-dry 3–4 days on clean mat",
              "Winnow, grade and bag for milling",
            ],
            "Test maturity by cutting 10 pods — chocolate-brown inner testa means ready to lift.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Brinjal (var. MHB-10 hybrid)",
        "High-Value Market Vegetable",
        "MHB-10 yields early and profusely in the Ghat summer with drip irrigation. Igatpuri's cooler nights reduce fruit drop, while strong Nashik–Pune demand for glossy purple fruit keeps prices firm through April.",
        "Transplant 800–1000 seedlings/acre at 90×60cm. Drip fertigate weekly with 20:20:20. Prune lower leaves for airflow and harvest every 3 days.",
        "Transplant in February after nursery sowing in January",
        120,
        "Coriander inter-row; onion sequence",
        "15–20 t/acre over 15–18 weekly pickings",
        "Lakadbagh hybrids earn ₹15–25/kg at Nashik mandi; pre-monsoon summer window is a price peak.",
        "Medium–high: drip at 6–8 L/plant/day through summer.",
        {
          yieldPotential: 85,
          marketValue: 74,
          waterEfficiency: 55,
          soilCompatibility: 70,
          climateResilience: 70,
        },
        { inputCostPerAcre: 22000, grossRevenuePerAcre: 71000, netProfitPerAcre: 49000 },
        wc(
          ["Nursery/Sowing", 30],
          ["Vegetative", 160],
          ["Flowering/Panicle", 200],
          ["Maturity/Harvest", 220],
        ),
        {
          primaryPests: ["Shoot and fruit borer", "Epilachna beetle", "Whitefly"],
          primaryDiseases: ["Phomopsis blight", "Little leaf (phytoplasma)", "Wilt"],
          riskLevel: "high",
          ipmAdvice: [
            "Remove infested shoots/fruits every picking — the borer's biggest weak point.",
            "Yellow sticky traps (12/ha) against whitefly.",
            "Drench with Pseudomonas fluorescens at transplanting against wilt.",
          ],
          symptoms: [
            "Bored fruit with frass plugs",
            "Wilting of young shoots",
            "Small crinkled leaves (little leaf disease)",
          ],
        },
        stages([
          [
            "Nursery & Transplanting",
            30,
            "sowing",
            [
              "Raise nursery on raised beds; 200g seed for 1 acre",
              "Transplant 30–35 day seedlings at 90×60cm",
              "Basal 20:40:40 NPK",
            ],
            "Keep 20% more seedlings for gap filling — early uniformity pays through the season.",
          ],
          [
            "Vegetative Growth",
            30,
            "irrigation",
            [
              "Drip 6–8 L/plant/day",
              "Two-sided hoeing at 25 days",
              "Install stakes for heavy hybrids",
            ],
            "Avoid flooding — drip keeps soil moisture steady and cuts flower drop.",
          ],
          [
            "Flowering & Fruiting",
            40,
            "fertilization",
            [
              "Weekly fertigation with 20:20:20 at 3kg/acre",
              "Top-dress 25kg N after first picking",
              "Prune lower shaded leaves monthly",
            ],
            "Pinch off the first flush of flowers to build plant frame — more fruit later.",
          ],
          [
            "Picking & Harvest",
            20,
            "harvest",
            [
              "Harvest every 3rd day; never over-mature",
              "Grade by size and gloss",
              "Dispatch same evening for morning mandi",
            ],
            "Brinjal is a price-taker — time picking to Tuesday–Saturday wholesale peaks.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Bottle Gourd / Lauki (var. Pusa Naveen)",
        "Summer Cucurbit Cash Crop",
        "A fast summer crop on the well-drained Ghat slopes, bottle gourd capitalises on pre-monsoon vegetable scarcity. It climbs trellises efficiently under drip, producing 15+ tonnes that move fast through Nashik's summer mandi.",
        "Sow 2 seeds per pit at 2.5×1m on raised beds. Train vines on 6ft trellis. Drip 10 L/plant/day at peak; harvest fruits at 30–40cm length.",
        "March (second crop in May)",
        85,
        "Chilli inter-row; marigold border as trap crop",
        "12–15 t/acre over 10–12 weekly pickings",
        "Summer gourd shortage in Mumbai lifts prices to ₹12–20/kg at Nashik wholesale.",
        "Medium: 25–30cm water over the season via drip; efficient per unit fruit.",
        {
          yieldPotential: 80,
          marketValue: 70,
          waterEfficiency: 52,
          soilCompatibility: 66,
          climateResilience: 66,
        },
        { inputCostPerAcre: 16000, grossRevenuePerAcre: 48000, netProfitPerAcre: 32000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 180],
          ["Flowering/Panicle", 230],
          ["Maturity/Harvest", 200],
        ),
        {
          primaryPests: ["Fruit fly", "Red pumpkin beetle", "Aphid"],
          primaryDiseases: ["Downy mildew", "Powdery mildew", "Mosaic virus"],
          riskLevel: "medium",
          ipmAdvice: [
            "Install cue-lure traps (10/ha) for fruit fly — the top gourd pest.",
            "Spray azadirachtin 0.3% against beetles early morning.",
            "Remove virus-diseased plants promptly.",
          ],
          symptoms: [
            "Sunken, brown, half-rotten spots on young fruits",
            "White powdery coating on leaves in late summer",
            "Mosaic yellowing and leaf distortion",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 2 seeds/pit at 2.5×1m",
              "Apply 20:40:40 + FYM in pits",
              "Install trellis before vine spread",
            ],
            "Raise vines on trellis — ground vines rot and fruit-fly damage escalates.",
          ],
          [
            "Vegetative Growth",
            30,
            "irrigation",
            [
              "Drip 6 L/plant/day; increase with canopy",
              "Pinch side shoots beyond 8th node",
              "Mulch with straw for moisture retention",
            ],
            "Train two main vines only — fewer vines, bigger, cleaner fruit.",
          ],
          [
            "Flowering & Fruit Set",
            30,
            "fertilization",
            [
              "Weekly fertigation 19:19:19",
              "Spray boron 0.2% at flower initiation",
              "Cue-lure trap servicing weekly",
            ],
            "Female flowers dominate the lower nodes; hand-pollinate in heat waves to avoid fruit drop.",
          ],
          [
            "Maturity & Harvest",
            13,
            "harvest",
            [
              "Harvest fruits at 30–40cm; pick every 4–5 days",
              "Cut with 2cm stalk; pack in ventilated crates",
              "Dispatch within 12 hours",
            ],
            "Over-mature gourds turn fibrous and break the premium; regular picking extends yield.",
          ],
        ]),
      ),
    ],
  },
  central: {
    kharif: [
      makeCrop(
        "primary",
        "Bt Cotton Hybrid (var. MRC-7347)",
        "Primary Recommended Crop",
        "Deep black cotton soil of the Godavari basin retains monsoon moisture perfectly for cotton. Hybrid Bt gives robust boll development under canal-assured water, and Nashik's strong ginning cluster guarantees a ready market for kapas.",
        "Sow 1.6kg delinted seed/acre at 90×60cm after soil drenching. Basal 25:50:25 NPK. Stop nitrogen after 90 days to avoid rank growth that invites bollworm.",
        "Second fortnight of June (after 15cm rainfall or one irrigation)",
        170,
        "Soybean border rows; coriander as undercrop",
        "10–12 quintal/acre of kapas",
        "Kapas at Niphad ginners quotes ₹7,000–8,500/quintal; forward-sale options reduce price risk.",
        "Medium: monsoon + 4–5 protective irrigations; sensitive to waterlogging in black soil.",
        {
          yieldPotential: 78,
          marketValue: 80,
          waterEfficiency: 55,
          soilCompatibility: 90,
          climateResilience: 70,
        },
        { inputCostPerAcre: 20000, grossRevenuePerAcre: 56000, netProfitPerAcre: 36000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 260],
          ["Flowering/Panicle", 360],
          ["Maturity/Harvest", 180],
        ),
        {
          primaryPests: ["Pink bollworm", "Sucking pests (jassid, thrips)", "Spotted bollworm"],
          primaryDiseases: ["Bacterial blight", "Root rot", "Leaf curl virus"],
          riskLevel: "high",
          ipmAdvice: [
            "Install pink bollworm pheromone traps (10/ha) from 60 days; follow PBW rope timed release.",
            "Spray imidacloprid 17.8SL only when jassid crosses 10/leaf.",
            "Rogue out leaf-curl infected plants with whitefly colonies early.",
          ],
          symptoms: [
            "Rosette / 'parrot-beak' damaged bolls (pink bollworm)",
            "Cupped, yellowing leaves with jassid burn",
            "Vein-clearing and leaf curl in young plants",
          ],
        },
        stages([
          [
            "Sowing",
            15,
            "sowing",
            [
              "Sow 1.6kg delinted seed/acre at 90×60cm",
              "Basal 25:50:25 NPK in furrows",
              "First irrigation within 10 days if no rain",
            ],
            "Delay sowing past mid-July — late cotton invites pink bollworm late in the season.",
          ],
          [
            "Vegetative Growth",
            55,
            "irrigation",
            [
              "Irrigate at 12–15 day intervals",
              "Thin to one healthy seedling/hill",
              "Weed control with two mechanical hoeings",
            ],
            "Black soil holds water — over-irrigating early causes rank growth and root rot.",
          ],
          [
            "Flowering & Boll Formation",
            65,
            "fertilization",
            [
              "Top-dress 25kg N at squaring (45 days)",
              "Second top-dress 25kg N at peak flowering",
              "PBW trap servicing and weekly scouting",
            ],
            "Gap water at peak flowering — moisture stress at squaring drops boll retention hard.",
          ],
          [
            "Maturity & Harvest",
            35,
            "harvest",
            [
              "Pick at 15-day intervals as bolls burst",
              "Dry kapas on clean tarpaulin for 2 days",
              "Grade by trash and moisture content",
            ],
            "Never pick wet kapas — moisture stains lint and ginners penalise the lot.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Soybean (var. JS-335)",
        "High-Value Protein Cash Crop",
        "Soybean exploits the same Godavari black soil with just 90–100 days, syncing perfectly with the kharif window before rabi onion land prep. JS-335's bold seeds command the crush plant price at Niphad's oil-extraction units.",
        "Sow 25kg seed/acre at 45×5cm with seed inoculation of Rhizobium japonicum. Basal 10:40:20 NPK. Harvest at 90% pod maturity before the field cracks.",
        "Mid-June to early July",
        95,
        "Pigeon pea border; soybean–cotton intercropping",
        "800–1000 kg/acre of bold seed",
        "Soybean meal and seed trade at Niphad; price ₹4,200–5,200/quintal.",
        "Medium: 3–4 protective irrigations; sensitive to both drought and waterlogging.",
        {
          yieldPotential: 72,
          marketValue: 78,
          waterEfficiency: 66,
          soilCompatibility: 85,
          climateResilience: 68,
        },
        { inputCostPerAcre: 12000, grossRevenuePerAcre: 42000, netProfitPerAcre: 30000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 180],
          ["Flowering/Panicle", 220],
          ["Maturity/Harvest", 60],
        ),
        {
          primaryPests: ["Tobacco caterpillar (Spodoptera)", "Semi-looper", "Girdle beetle"],
          primaryDiseases: ["Yellow mosaic virus", "Anthracnose", "Collateral stem rot"],
          riskLevel: "medium",
          ipmAdvice: [
            "Erect bird perches for predatory birds from 30 days.",
            "Spray NPV 250 LE/acre against Spodoptera larvae.",
            "Yellow sticky traps for whitefly vector of YMV.",
          ],
          symptoms: [
            "Bright yellow mosaic mottling of young leaves",
            "Shot-hole and skeletonised leaves",
            "Girdling rings on main stem (girdle beetle)",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 25kg seed/acre at 45×5cm",
              "Inoculate with Rhizobium japonicum",
              "Basal 10:40:20 NPK",
            ],
            "Sow at 3–4cm only — deep sowing strangles soybean emergence.",
          ],
          [
            "Vegetative Growth",
            35,
            "irrigation",
            [
              "Irrigate at 15-day intervals",
              "Two mechanical weedings",
              "Thin to 8–10 plants per running metre",
            ],
            "Soybean flowers at 40–50 days; protect the crop from any moisture stress just before.",
          ],
          [
            "Flowering & Pod Fill",
            35,
            "fertilization",
            [
              "Spray 0.2% boron at flowering",
              "Top-dress 10kg N at pod initiation",
              "Weekly Spodoptera scouting",
            ],
            "Yellow mosaic hits hardest early — keep whitefly off from the start.",
          ],
          [
            "Maturity & Harvest",
            15,
            "harvest",
            [
              "Harvest at 90% pod maturity",
              "Thresh carefully; avoid seed cracking",
              "Dry to 10% moisture and bag for oil mill",
            ],
            "Cracked seed discounts heavily at crushers — thresh gently on a clean floor.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Bajra / Pearl Millet (var. ICTP-8203)",
        "Drought-Hardy Option",
        "For black-soil fields with weaker irrigation security, ICTP-8203 pearl millet matures in under 90 days with just monsoon moisture. It frees the field for a full rabi onion cycle — a strategic double-cropping ace.",
        "Sow 2.5kg seed/acre at 45×15cm in the first good June rain. Top-dress 25kg N at 35 days. Harvest when 80% earheads dry.",
        "First to third week of June",
        85,
        "Pigeon pea (2:1 row); cowpea on bunds",
        "12–15 quintal/acre of grain",
        "Bajra moves steadily at Lasalgaon as feed and flour; ₹1,800–2,300/quintal.",
        "Low: rainfed; 1–2 life-saving irrigations only in a monsoon break.",
        {
          yieldPotential: 62,
          marketValue: 65,
          waterEfficiency: 85,
          soilCompatibility: 75,
          climateResilience: 82,
        },
        { inputCostPerAcre: 8000, grossRevenuePerAcre: 26000, netProfitPerAcre: 18000 },
        wc(
          ["Nursery/Sowing", 35],
          ["Vegetative", 150],
          ["Flowering/Panicle", 170],
          ["Maturity/Harvest", 50],
        ),
        {
          primaryPests: ["Shoot fly", "Downy mildew (green ear)", "Armyworm"],
          primaryDiseases: ["Downy mildew", "Ergot", "Smut"],
          riskLevel: "low",
          ipmAdvice: [
            "Seed-treat with metalaxyl against downy mildew.",
            "Adjust sowing to 15 June+ to dodge shoot fly peak.",
            "Remove ergot-infected earheads before they shed.",
          ],
          symptoms: [
            "Green leafy outgrowths replacing grains (green ear)",
            "Stunted, purplish tillers",
            "Honeydew followed by dark ergot bodies on earheads",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 2.5kg/acre at 45×15cm",
              "Basal 10:20:20 NPK",
              "Seed-treat with metalaxyl",
            ],
            "Line sowing saves seed and makes the single mechanical hoeing effective.",
          ],
          [
            "Vegetative Growth",
            35,
            "irrigation",
            [
              "Single hoeing + earthing at 25 days",
              "Irrigate if dry spell crosses 18 days",
              "Top-dress 25kg N at 35 days",
            ],
            "Bajra's taproot goes deep — a light recharge beats frequent shallow watering.",
          ],
          [
            "Flowering & Grain Fill",
            25,
            "fertilization",
            [
              "Spray 0.5% potassium nitrate at flowering",
              "Monitor armyworm in earhead stage",
              "Avoid late nitrogen — delays maturity",
            ],
            "Green-ear (downy mildew) shows at flowering; rogue out infected earheads.",
          ],
          [
            "Maturity & Harvest",
            15,
            "harvest",
            [
              "Harvest at 80% dry earheads",
              "Cut, stack and thresh",
              "Winnow and dry grain to 12%",
            ],
            "Dry threshed grain fast — warm humid spells after kharif spoil moisture content.",
          ],
        ]),
      ),
    ],
    rabi: [
      makeCrop(
        "primary",
        "Export-grade Thompson Seedless Grapes",
        "High-Value Cash Crop",
        "Niphad's warm winters, assured canal-plus-drip water and deep black soil create the world-class terroir that made Nashik India's grape bowl. Thompson Seedless trained on drip yields juicy, seedless export-grade bunches that European buyers chase.",
        "Plant rooted cuttings at 3×3m in December–February; complete the first fruiting trellis (bower) in year one. Drip-feed 35–40 L/vine/day through the season.",
        "Planting: December–February; annual pruning cycles from year 2",
        300,
        "Strawberry or early onion between young vine rows",
        "6–8 t/acre first fruiting; 10–12 t/acre mature vines",
        "Export to EU/UK via Mahagrape cluster; ₹70–110/kg at vineyard gate for export-grade bunches.",
        "High: drip at 2.2–2.6 ac-ft/acre/year, scheduled around critical berry stages.",
        {
          yieldPotential: 76,
          marketValue: 95,
          waterEfficiency: 62,
          soilCompatibility: 85,
          climateResilience: 65,
        },
        { inputCostPerAcre: 60000, grossRevenuePerAcre: 190000, netProfitPerAcre: 130000 },
        wc(
          ["Nursery/Sowing", 90],
          ["Vegetative", 480],
          ["Flowering/Panicle", 520],
          ["Maturity/Harvest", 350],
        ),
        {
          primaryPests: ["Mealybug", "Thrips", "Mites"],
          primaryDiseases: ["Powdery mildew", "Downy mildew", "Anthracnose"],
          riskLevel: "high",
          ipmAdvice: [
            "Follow a strict sulphur–copper spray calendar timed to vine phenology.",
            "Strip bark and drench with chlorpyriphos in dormancy against mealybug hideouts.",
            "Expose bunches by leaf plucking to cut mildew pressure.",
          ],
          symptoms: [
            "White powdery coating on berries and canes",
            "Cottony masses in bunch axils (mealybug)",
            "Oily translucent spots on leaves (downy mildew)",
          ],
        },
        stages([
          [
            "Planting & Establishment",
            60,
            "sowing",
            [
              "Plant rooted cuttings at 3×3m; install drip",
              "Grow trellis arms; single-stem training",
              "Milk-run trunk canes; remove flowers in year 1",
            ],
            "A thick, straight trunk built in year one determines the vine's entire economic life.",
          ],
          [
            "Vegetative Growth",
            90,
            "irrigation",
            [
              "Drip 30–40 L/vine/day in summer",
              "Stop irrigation 30 days before pruning",
              "Spray copper-based fungicide at bud burst",
            ],
            "Withhold water before pruning to harden canes and force even bud-break.",
          ],
          [
            "Flowering & Berry Set",
            80,
            "fertilization",
            [
              "Fertigate 19:19:19 through bloom",
              "GA3 treatment for berry elongation",
              "Thin to 1 bunch per shoot",
            ],
            "Time GA3 to 50% cap-fall for the elongated seedless berry exporters expect.",
          ],
          [
            "Maturity & Harvest",
            70,
            "harvest",
            [
              "Harvest at 16–18° Brix with 3–4g berry size",
              "Cool bunch to 2°C within 2 hours",
              "Pack in export cartons with SO2 pads",
            ],
            "Grading by Brix and berry size decides EU acceptance — reject underweight bunches.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Rabi Onion 'Nashik Red' (var. Bhima Super)",
        "Export-grade Bulb Crop",
        "Niphad's black soil and cool rabi nights produce the prized firm, red, pungent Nashik onion. Bhima Super yields 12–18 t/acre and rides the storability premium that makes Pimpalgaon–Lasalgaon the world's largest onion market.",
        "Sow nursery in September; transplant 25–30 day seedlings at 15×10cm (6 lakh/acre). Basal 25:50:50 NPK. Stop irrigation 15 days before harvest for skin formation.",
        "Nursery: September; transplanting: October–November",
        130,
        "Fenugreek in borders; gram sequence",
        "12–18 t/acre of cured bulbs",
        "Lasalgaon & Pimpalgaon APMC are India's onion price-setters; export-grade reds earn ₹1,500–2,200/quintal.",
        "Medium–high: 10–12 irrigations; drip optional but cuts water use 35%.",
        {
          yieldPotential: 88,
          marketValue: 90,
          waterEfficiency: 60,
          soilCompatibility: 85,
          climateResilience: 75,
        },
        { inputCostPerAcre: 35000, grossRevenuePerAcre: 110000, netProfitPerAcre: 75000 },
        wc(
          ["Nursery/Sowing", 60],
          ["Vegetative", 320],
          ["Flowering/Panicle", 260],
          ["Maturity/Harvest", 140],
        ),
        {
          primaryPests: ["Onion thrips", "Onion maggot", "Cutworm"],
          primaryDiseases: ["Purple blotch", "Stemphylium blight", "Downy mildew"],
          riskLevel: "high",
          ipmAdvice: [
            "Thrips hit worst in dry spells — irrigate on time; spray spinosad at 15 thrips/plant.",
            "Alternate fungicides (mancozeb ↔ azoxystrobin) against purple blotch.",
            "Crop rotation away from Alliums every 2 years.",
          ],
          symptoms: [
            "Silvery streaking and curling leaf tips (thrips)",
            "Sunken purplish spots with concentric rings",
            "White oval lesions on older leaves (stemphylium)",
          ],
        },
        stages([
          [
            "Nursery & Transplanting",
            35,
            "sowing",
            [
              "Raise nursery September; 4kg seed/acre",
              "Transplant 25–30 day seedlings at 15×10cm",
              "Basal 25:50:50 NPK at transplant",
            ],
            "Sturdy, pencil-thick seedlings transplant best — soft etiolated seedlings crush yield.",
          ],
          [
            "Vegetative Growth",
            60,
            "irrigation",
            [
              "Irrigate weekly; keep field weed-free",
              "Top-dress 25kg N at 45 days",
              "Hoe between rows twice",
            ],
            "Bulb initiation needs uninterrupted moisture — any hard stress makes bolters.",
          ],
          [
            "Bulb Development",
            25,
            "fertilization",
            [
              "Potassium top-dress 25kg at bulb swell",
              "Spray mancozeb against purple blotch",
              "Thrips scouting twice weekly",
            ],
            "Cessation of new foliage signals bulbing; protect leaves to feed the bulb.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Stop irrigation 15 days before lifting",
              "Lift bulbs, cure in windrows 7 days",
              "Top, grade and bag for Lasalgaon",
            ],
            "Well-cured necks (skin tight) decide the storage premium — rushing curing bleeds money.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Rabi Tomato (var. Abhinav / Rani)",
        "High-Return Vegetable",
        "With assured Niphad irrigation, rabi tomato locks into the February–April price spike before the monsoon glut. Abhinav's firm, deep-red fruit ships well to Mumbai, giving a fast 120-day cash cycle on the same black soil.",
        "Raise nursery October; transplant 5000 seedlings/acre at 120×60cm with drip. Fertigate weekly; stake and prune to two stems. Stop water 10 days before final harvest.",
        "Transplant: November–December (harvest Feb–Apr)",
        135,
        "Onion inter-row; marigold border as nematode trap",
        "18–25 t/acre over 8–10 pickings",
        "Nashik–Mumbai wholesale pays ₹12–22/kg in the lean Feb–Apr window.",
        "Medium–high: 15–18 irrigations or drip 8–10 L/plant/day.",
        {
          yieldPotential: 85,
          marketValue: 80,
          waterEfficiency: 55,
          soilCompatibility: 80,
          climateResilience: 62,
        },
        { inputCostPerAcre: 45000, grossRevenuePerAcre: 120000, netProfitPerAcre: 75000 },
        wc(
          ["Nursery/Sowing", 50],
          ["Vegetative", 300],
          ["Flowering/Panicle", 330],
          ["Maturity/Harvest", 260],
        ),
        {
          primaryPests: ["Fruit borer (Helicoverpa)", "Whitefly", "Aphid"],
          primaryDiseases: ["Early blight", "Late blight", "Bacterial wilt"],
          riskLevel: "high",
          ipmAdvice: [
            "Install Helicoverpa pheromone traps (10/ha) from flowering.",
            "Weekly alternating fungicide sprays through the cool wet winter.",
            "Graft on resistant rootstocks to dodge bacterial wilt in black soil.",
          ],
          symptoms: [
            "Bored fruits with frass; holes on young green fruit",
            "Brown concentric spots on older leaves",
            "Sudden wilting with white bacterial ooze from cut stem",
          ],
        },
        stages([
          [
            "Nursery & Transplanting",
            30,
            "sowing",
            [
              "Raise nursery October; 120g seed/acre",
              "Transplant 5000 seedlings at 120×60cm",
              "Basal 25:50:50 NPK",
            ],
            "Transplant in the evening and irrigate immediately — evening transplanting cuts wilt.",
          ],
          [
            "Vegetative Growth",
            35,
            "irrigation",
            [
              "Drip 8–10 L/plant/day",
              "Install stakes; prune to two stems",
              "Hoe and mulch between rows",
            ],
            "Keep the canopy open — airflow is the cheapest disease insurance in humid winters.",
          ],
          [
            "Flowering & Fruit Set",
            40,
            "fertilization",
            [
              "Weekly fertigation 19:19:19",
              "Spray calcium nitrate at fruit set against blossom-end rot",
              "Weekly Helicoverpa scouting",
            ],
            "Calcium at fruit set is non-negotiable on black soil with high moisture swings.",
          ],
          [
            "Maturity & Harvest",
            30,
            "harvest",
            [
              "Pick at breaker-to-pink stage for distant market",
              "Grade by size; pack in 20kg crates",
              "Dispatch overnight to Mumbai",
            ],
            "Pink-stage fruit ships better; vine-ripe only for the nearest mandi.",
          ],
        ]),
      ),
    ],
    summer: [
      makeCrop(
        "primary",
        "Summer Green Gram / Moong (var. SML-668)",
        "Primary Recommended Crop",
        "SML-668's lightning 65–75 day cycle turns a short Sinnar summer gap into a high-value pulse crop. Moong's nitrogen fixation improves the black soil for the following kharif, and summer moong prices at Lasalgaon are consistently strong.",
        "Sow 10kg seed/acre at 30×10cm on residual winter moisture plus 2–3 irrigations. Seed-treat with Rhizobium. Harvest at 90% pod maturity; dry to 10% moisture.",
        "First fortnight of March",
        70,
        "Short-duration cowpea inter-row; bajra sequence",
        "400–600 kg/acre of clean grain",
        "Summer moong scarcity pushes Lasalgaon prices to ₹8,000–9,500/quintal.",
        "Low–medium: 3–4 protective irrigations total; completes before peak heat.",
        {
          yieldPotential: 68,
          marketValue: 88,
          waterEfficiency: 70,
          soilCompatibility: 80,
          climateResilience: 78,
        },
        { inputCostPerAcre: 9000, grossRevenuePerAcre: 36000, netProfitPerAcre: 27000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 150],
          ["Flowering/Panicle", 140],
          ["Maturity/Harvest", 40],
        ),
        {
          primaryPests: ["Pod borer", "Whitefly (YMV)", "Aphid"],
          primaryDiseases: ["Yellow mosaic virus", "Powdery mildew", "Root rot"],
          riskLevel: "medium",
          ipmAdvice: [
            "Yellow sticky traps from emergence against YMV whitefly vectors.",
            "Seed treatment with carbendazim beats root rot in warm soil.",
            "Spray neem oil 2% at flowering for pod borer.",
          ],
          symptoms: [
            "Yellow mosaic mottling on young leaves",
            "White powdery patches in warm dry spells",
            "Damping-off and seedling collapse in hot soil",
          ],
        },
        stages([
          [
            "Sowing",
            8,
            "sowing",
            [
              "Sow 10kg/acre at 30×10cm",
              "Inoculate seed with Rhizobium",
              "Light irrigation to sprout",
            ],
            "Sow shallow (3–4cm) into slightly moist soil — crusting in black soil blocks emergence.",
          ],
          [
            "Vegetative Growth",
            25,
            "irrigation",
            [
              "Two hoeings before flowering",
              "Irrigate at 10-day intervals",
              "Thin to 15–20 plants per metre",
            ],
            "Summer heat accelerates the cycle — never let weeds compete for scarce moisture.",
          ],
          [
            "Flowering & Pod Set",
            25,
            "fertilization",
            [
              "Spray 0.2% boron at flower initiation",
              "Top-dress 5kg N at podding",
              "Weekly pod borer monitoring",
            ],
            "Moong sets pods quickly in heat — a single good flowering flush carries the yield.",
          ],
          [
            "Maturity & Harvest",
            12,
            "harvest",
            [
              "Harvest at 90% pod maturity; early morning",
              "Dry pods 2–3 days; thresh gently",
              "Winnow and bag for Lasalgaon dal trade",
            ],
            "Dry to 10% moisture — split moong seeds downgrade to feed grade.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Summer Onion (var. Phule Samarth)",
        "Market-topping Bulb Crop",
        "A summer onion on central black soil rides the April–May scarcity window at Pimpalgaon. Phule Samarth is heat-tolerant and short-day, bulbing in the long summer days with drip irrigation on the assured canal belt.",
        "Transplant 5 lakh seedlings/acre at 15×10cm from a February nursery. Drip-feed with weekly 19:19:19 fertigation. Stop water 12 days before lifting.",
        "Nursery: February; transplanting: March",
        115,
        "Fenugreek border; green gram sequence",
        "10–14 t/acre of cured bulbs",
        "Pre-monsoon onion shortage pushes Lasalgaon to ₹2,200–3,000/quintal for firm reds.",
        "Medium: drip at 40cm depth schedule; 12–14 irrigations.",
        {
          yieldPotential: 80,
          marketValue: 86,
          waterEfficiency: 66,
          soilCompatibility: 82,
          climateResilience: 70,
        },
        { inputCostPerAcre: 30000, grossRevenuePerAcre: 76000, netProfitPerAcre: 46000 },
        wc(
          ["Nursery/Sowing", 55],
          ["Vegetative", 290],
          ["Flowering/Panicle", 240],
          ["Maturity/Harvest", 130],
        ),
        {
          primaryPests: ["Onion thrips", "Cutworm"],
          primaryDiseases: ["Purple blotch", "Basal rot", "Downy mildew"],
          riskLevel: "high",
          ipmAdvice: [
            "Summer thrips explode fast — use blue sticky traps and threshold-based sprays.",
            "Spray mancozeb weekly through bulb swell.",
            "Harvest and cure thoroughly — summer heat cures onions fast.",
          ],
          symptoms: [
            "Silvery streaking and stunting of leaves",
            "Sunken purple lesions expanding to tip dieback",
            "Soft rot at bulb base in damp pockets",
          ],
        },
        stages([
          [
            "Nursery & Transplanting",
            35,
            "sowing",
            [
              "Raise nursery February; 4kg seed/acre",
              "Transplant 5 lakh seedlings at 15×10cm",
              "Basal 25:50:50 NPK",
            ],
            "Summer sun scorches transplants — transplant late afternoon and shade 3 days.",
          ],
          [
            "Vegetative Growth",
            50,
            "irrigation",
            [
              "Drip 8–10 L/m²/week; increase with heat",
              "Top-dress 25kg N at 45 days",
              "Hoe between rows twice",
            ],
            "Drip under black mulch cuts evaporation 40% and thrips pressure.",
          ],
          [
            "Bulb Development",
            20,
            "fertilization",
            [
              "Potassium top-dress at bulb swell",
              "Continue blotch sprays",
              "Withhold irrigation 12 days pre-harvest",
            ],
            "Sharp moisture cut triggers skin formation — the key to storage and price.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Lift bulbs in morning; cure in windrows 6–7 days",
              "Top and grade by diameter",
              "Dispatch to Pimpalgaon or cold store",
            ],
            "Grade hard by size — premium grade moves first at Lasalgaon auction.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Sweet Corn (var. Sugar-75)",
        "Fast Summer Cash Crop",
        "A 75–85 day sweet corn crop turns summer irrigation into quick cash before the monsoon. Sugar-75 cobs fetch strong summer prices at Nashik's vegetable market and the crop's fodder feeds local dairy — a tidy double income.",
        "Sow 3.5kg seed/acre at 75×25cm with drip. Basal 20:40:40 NPK; top-dress 30kg N split at knee-high and tasselling. Harvest cobs at milk stage.",
        "March to early April",
        80,
        "Cowpea inter-row; tomato sequence",
        "9–11 t/acre of marketable cobs",
        "Fresh cobs at ₹8–14/kg wholesale; dairy villages buy the green fodder.",
        "Medium: 7–9 irrigations; drought-sensitive at tasselling.",
        {
          yieldPotential: 82,
          marketValue: 72,
          waterEfficiency: 65,
          soilCompatibility: 78,
          climateResilience: 75,
        },
        { inputCostPerAcre: 18000, grossRevenuePerAcre: 50000, netProfitPerAcre: 32000 },
        wc(
          ["Nursery/Sowing", 45],
          ["Vegetative", 200],
          ["Flowering/Panicle", 220],
          ["Maturity/Harvest", 90],
        ),
        {
          primaryPests: ["Fall armyworm", "Stem borer", "Aphid"],
          primaryDiseases: ["Leaf blight", "Rust", "Smut"],
          riskLevel: "medium",
          ipmAdvice: [
            "Scout for fall armyworm from 15 days; whorl treatment with emamectin benzoate.",
            "Milk-stage harvest beats smut build-up.",
            "Remove smutted ears promptly.",
          ],
          symptoms: [
            "Shot-hole whorl damage with frass (fall armyworm)",
            "Pinhole rows on leaves (stem borer)",
            "Grey smut galls replacing kernels",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 3.5kg/acre at 75×25cm",
              "Basal 20:40:40 NPK",
              "Drip line install; irrigate immediately",
            ],
            "Precision plant at one kernel every 25cm for uniform cob maturity.",
          ],
          [
            "Vegetative Growth",
            35,
            "irrigation",
            [
              "Irrigate at 6-day intervals in heat",
              "Top-dress 15kg N at knee-high",
              "First earthing-up",
            ],
            "Corn's yield is set by early vigour — keep it growing fast in summer heat.",
          ],
          [
            "Tasselling & Silking",
            25,
            "fertilization",
            [
              "Top-dress 15kg N at tasselling",
              "Ensure irrigation at silking — critical week",
              "Fall armyworm whorl check",
            ],
            "Silking-to-harvest is the drought-critical week; never stress it.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Harvest at milk stage (milky kernel exudate)",
              "Cut with husk; cool immediately",
              "Sell cobs; sell stalks as green fodder",
            ],
            "Milk-stage cobs — harvest the same morning you sell; sugars vanish within hours.",
          ],
        ]),
      ),
    ],
  },
  arid: {
    kharif: [
      makeCrop(
        "primary",
        "Bajra / Pearl Millet (var. GHB-905)",
        "Primary Recommended Crop",
        "Malegaon's 500–600mm rain-shadow rainfall is exactly the envelope GHB-905 pearl millet was bred for. Its deep root system and heat tolerance deliver grain on shallow calcareous soils where nothing else thrives, anchoring the whole arid-belt kharif economy.",
        "Sow 2.5kg seed/acre at 45×15cm in the first monsoon rain (June 15+). Seed-treat with metalaxyl. A single life-saving irrigation at 35 days protects the flowering flush.",
        "Mid-June to first week of July",
        85,
        "Pigeon pea (2:1 inter-row); cowpea on bunds",
        "10–14 quintal/acre of grain",
        "Steady feed/flour demand at Malegaon and Yeola; ₹1,800–2,400/quintal.",
        "Low: rainfed; 1–2 life-saving irrigations in a monsoon break.",
        {
          yieldPotential: 70,
          marketValue: 68,
          waterEfficiency: 95,
          soilCompatibility: 72,
          climateResilience: 92,
        },
        { inputCostPerAcre: 6500, grossRevenuePerAcre: 22000, netProfitPerAcre: 15500 },
        wc(
          ["Nursery/Sowing", 35],
          ["Vegetative", 150],
          ["Flowering/Panicle", 170],
          ["Maturity/Harvest", 50],
        ),
        {
          primaryPests: ["Shoot fly", "Downy mildew (green ear)", "Armyworm"],
          primaryDiseases: ["Downy mildew", "Ergot", "Smut"],
          riskLevel: "low",
          ipmAdvice: [
            "Delay sowing to 15 June to skip the shoot-fly window.",
            "Metalaxyl seed treatment stops downy mildew at source.",
            "Remove green-ear heads before spores spread.",
          ],
          symptoms: [
            "Leafy outgrowths replacing grain (green ear)",
            "Stunted purplish tillers",
            "Dark ergot bodies on earheads",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 2.5kg/acre at 45×15cm",
              "Basal 10:20:20 NPK",
              "Metalaxyl seed treatment",
            ],
            "Sow only after 3–4cm of effective rainfall — early sowing on dry seed beds fails in arid soils.",
          ],
          [
            "Vegetative Growth",
            35,
            "irrigation",
            [
              "Single hoeing + earthing at 25 days",
              "Life-saving irrigation at 35 days if dry",
              "Top-dress 25kg N at 40 days",
            ],
            "The taproot mines deep moisture — one well-timed irrigation beats four shallow ones.",
          ],
          [
            "Flowering & Grain Fill",
            25,
            "fertilization",
            [
              "Spray 0.5% potassium nitrate at flowering",
              "Monitor armyworm in earhead stage",
              "No late nitrogen",
            ],
            "Green-ear shows at flowering — rogue out infected heads fast in arid heat.",
          ],
          [
            "Maturity & Harvest",
            15,
            "harvest",
            [
              "Harvest at 80% dry earheads",
              "Stack, thresh and winnow",
              "Dry to 12% moisture before bagging",
            ],
            "Dry threshed grain immediately — arid-zone humidity spikes after cyclonic spells.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Bhagwa Pomegranate (Orchard)",
        "Drought-Hardy High-Value Orchard",
        "Malegaon's dry heat and mild winters are ideal for Bhagwa pomegranate — the export superstar that shrugs off drought with drip irrigation. Arid soils actually produce the deep-red, hard-rind fruit that Gulf and EU buyers pay a premium for.",
        "Plant grafts at 4×3m after puddling pits with FYM + PSB. Establish drip from day one. Prune to single-stem, allow 4–6 scaffolds. First commercial harvest at 18 months.",
        "Planting: June–August with monsoon; annual bhāv cycles thereafter",
        540,
        "Lemongrass or cowpea in young orchard alleys",
        "5–7 t/acre from mature trees (12–18 t/ha)",
        "Export grade Bhagwa: ₹90–150/kg to UAE/EU; domestic ₹50–80/kg at Malegaon.",
        "Medium: drip at 1,200–1,600mm/year for full bearing; strictly scheduled in bhav stages.",
        {
          yieldPotential: 78,
          marketValue: 88,
          waterEfficiency: 60,
          soilCompatibility: 75,
          climateResilience: 90,
        },
        { inputCostPerAcre: 50000, grossRevenuePerAcre: 135000, netProfitPerAcre: 85000 },
        wc(
          ["Nursery/Sowing", 150],
          ["Vegetative", 420],
          ["Flowering/Panicle", 420],
          ["Maturity/Harvest", 350],
        ),
        {
          primaryPests: ["Pomegranate butterfly (fruit borer)", "Aphids", "Thrips"],
          primaryDiseases: ["Bacterial blight", "Fruit cracking", "Anthracnose"],
          riskLevel: "high",
          ipmAdvice: [
            "Weekly bacterial blight spray program (Streptocycline + copper) — the #1 orchard threat.",
            "Bagging young fruits with waxed paper beats the butterfly without sprays.",
            "Mulch and regulated drip cut fruit cracking in summer heat.",
          ],
          symptoms: [
            "Black necrotic spots with halo on fruit (bacterial blight)",
            "Bore holes with frass in arils",
            "Longitudinal cracks on mature fruit",
          ],
        },
        stages([
          [
            "Planting & Establishment",
            90,
            "sowing",
            [
              "Plant grafts at 4×3m in FYM-filled pits",
              "Install drip (4 emitters/tree)",
              "Stake; single-stem training",
            ],
            "Train a straight single stem to 60cm before allowing scaffolds — frame decides orchard life.",
          ],
          [
            "Vegetative Growth",
            150,
            "irrigation",
            [
              "Drip 20–25 L/tree/day in year 1",
              "Weed-free basins; mulching",
              "Tip-prune to force branching",
            ],
            "Young trees need only 60% of mature water — over-irrigation delays fruiting.",
          ],
          [
            "First Flowering & Fruiting",
            180,
            "fertilization",
            [
              "Fertigate 19:19:19 monthly in flowering",
              "Spray zinc + boron pre-flowering",
              "Bag fruits to control fruit borer",
            ],
            "First commercial crop needs 'hardening' — restrict vegetative growth to force bloom.",
          ],
          [
            "Harvest & Cycle Management",
            120,
            "harvest",
            [
              "Harvest at 55–60% deep red colour; cool rind",
              "Grade by size and colour for export",
              "Plan next bhav: prune, defoliate, irrigate",
            ],
            "Time harvest on sugar/colour, not days — Bhagwa must hit export TSS ≥ 14°B.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Pigeon Pea / Tur (var. BDN-711)",
        "Risk-spreading Pulse",
        "Tur's deep taproot reaches water table in arid shallow soils, while its long cycle hedges against erratic monsoon distribution. BDN-711's wilt resistance and bold grain make it the desert-belt insurance crop with premium pulse economics.",
        "Sow 6kg seed/acre at 60×20cm after adequate rainfall (June end). Seed-treat with Trichoderma. Top-dress 20kg N at flowering; avoid late irrigation which fans pod borer.",
        "End June to mid-July",
        155,
        "Bajra (2:1 inter-crop); coriander under-storey",
        "5–7 quintal/acre of dal-grade grain",
        "Tur dal is chronically short; ₹8,000–10,000/quintal at Lasalgaon for clean grain.",
        "Low: rainfed; 1–2 life-saving irrigations only at pod fill.",
        {
          yieldPotential: 72,
          marketValue: 92,
          waterEfficiency: 75,
          soilCompatibility: 78,
          climateResilience: 85,
        },
        { inputCostPerAcre: 10000, grossRevenuePerAcre: 50000, netProfitPerAcre: 40000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 240],
          ["Flowering/Panicle", 300],
          ["Maturity/Harvest", 120],
        ),
        {
          primaryPests: ["Pod borer (Helicoverpa)", "Pod fly", "Sucking pests"],
          primaryDiseases: ["Fusarium wilt", "Sterility mosaic", "Phytophthora blight"],
          riskLevel: "medium",
          ipmAdvice: [
            "Pheromone traps (10/ha) from 90 days for Helicoverpa.",
            "Avoid dense sowing — crowding feeds sterility mosaic.",
            "Trichoderma seed treatment is the cheapest wilt insurance.",
          ],
          symptoms: [
            "Bored green pods with larvae",
            "Sudden yellowing and wilting (Fusarium)",
            "Mosaic mottling and stunted bushy growth",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 6kg/acre at 60×20cm",
              "Basal 10:20:20 NPK",
              "Trichoderma seed treatment",
            ],
            "Wide spacing is non-negotiable — tur needs air and light for healthy podding.",
          ],
          [
            "Vegetative Growth",
            70,
            "irrigation",
            [
              "Weed + hoe at 25 days",
              "Irrigate only if 25+ day dry spell",
              "Top-dress 20kg N at 60 days",
            ],
            "Tur survives on stored moisture — force it to root deep, not spread shallow.",
          ],
          [
            "Flowering & Pod Filling",
            60,
            "fertilization",
            [
              "Spray 0.2% boron at flower initiation",
              "Pheromone trap servicing weekly",
              "Single irrigation at pod fill if very dry",
            ],
            "Pod borer peaks at flowering — that 3-week window decides the dal premium.",
          ],
          [
            "Maturity & Harvest",
            13,
            "harvest",
            [
              "Harvest at 80% pod dryness; cut whole plants",
              "Stack 5–7 days; thresh",
              "Dry and bag for dal trade",
            ],
            "Never thresh wet — moisture splits dals and loses the top milling price.",
          ],
        ]),
      ),
    ],
    rabi: [
      makeCrop(
        "primary",
        "Rabi Jowar / Sorghum (var. Maldandi-35)",
        "Primary Recommended Crop",
        "The rain-shadow rabi window is jowar's home ground in Malegaon. Maldandi-35's lodging resistance and bold grain make it the traditional staple that stores well, feeds cattle, and delivers reliably on residual moisture with minimal irrigation.",
        "Sow 4kg seed/acre at 45×15cm in mid-October after a pre-sowing light irrigation. Top-dress 25kg N at tillering. Harvest at 80% grain dryness.",
        "October to mid-November",
        105,
        "Gram (2:1 inter-row); chickpea border",
        "8–12 quintal/acre of grain",
        "Rabi jowar demand at Malegaon for roti grain and feed; ₹1,700–2,300/quintal.",
        "Low: 2–3 protective irrigations; resilient on residual moisture.",
        {
          yieldPotential: 65,
          marketValue: 65,
          waterEfficiency: 85,
          soilCompatibility: 75,
          climateResilience: 88,
        },
        { inputCostPerAcre: 7000, grossRevenuePerAcre: 20000, netProfitPerAcre: 13000 },
        wc(
          ["Nursery/Sowing", 45],
          ["Vegetative", 200],
          ["Flowering/Panicle", 220],
          ["Maturity/Harvest", 80],
        ),
        {
          primaryPests: ["Shoot fly", "Stem borer", "Aphid"],
          primaryDiseases: ["Grain smut", "Rust", "Charcoal rot"],
          riskLevel: "low",
          ipmAdvice: [
            "Seed-treat with thiram against smut.",
            "Delay sowing past October 20 to dodge shoot fly.",
            "Avoid heavy late irrigation that feeds charcoal rot.",
          ],
          symptoms: [
            "Black smut balls replacing grain",
            "Dried grey-brown rust pustules",
            "Premature stalk drying (charcoal rot)",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 4kg/acre at 45×15cm",
              "Basal 10:20:20 NPK",
              "Pre-sowing irrigation if soil dry",
            ],
            "Rabi jowar needs a uniform stand — patchy stands compound moisture loss in arid fields.",
          ],
          [
            "Vegetative Growth",
            45,
            "irrigation",
            [
              "Irrigate at tillering (30 days)",
              "Single hoeing + earthing",
              "Top-dress 25kg N at 45 days",
            ],
            "The tillering irrigation buys the whole crop — apply it even in a light monsoon year.",
          ],
          [
            "Flowering & Grain Fill",
            35,
            "fertilization",
            [
              "Second irrigation at flowering if available",
              "Monitor stem borer",
              "Avoid late nitrogen",
            ],
            "Jowar is drought-tolerant but flowering stress cuts grain fill — protect it there.",
          ],
          [
            "Maturity & Harvest",
            15,
            "harvest",
            [
              "Harvest at 80% grain dryness",
              "Cut earheads; dry 3 days; thresh",
              "Store grain with neem leaf",
            ],
            "Dry to 12% — moist jowar ferments fast and burns in the feed market.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Gram / Chana (var. Digvijay)",
        "High-Value Rabi Pulse",
        "On the residual moisture of arid Malegaon soils, Digvijay gram converts cool rabi weather into premium pulse income with just one or two irrigations. Its wilt resistance and bold grain match the strong Lasalgaon dal demand.",
        "Sow 25kg seed/acre at 30×10cm immediately after the last October rain. Seed-treat with Trichoderma + carbendazim. Irrigate at pre-flowering (45 days) and pod filling.",
        "Mid-October to mid-November",
        105,
        "Mustard border; coriander inter-row",
        "650–850 kg/acre of clean grain",
        "Chana ₹5,000–6,500/quintal at Lasalgaon; strong local milling of the arid belt.",
        "Low: 2 irrigations; grows on residual moisture.",
        {
          yieldPotential: 66,
          marketValue: 88,
          waterEfficiency: 80,
          soilCompatibility: 75,
          climateResilience: 82,
        },
        { inputCostPerAcre: 7000, grossRevenuePerAcre: 28000, netProfitPerAcre: 21000 },
        wc(
          ["Nursery/Sowing", 50],
          ["Vegetative", 210],
          ["Flowering/Panicle", 250],
          ["Maturity/Harvest", 80],
        ),
        {
          primaryPests: ["Gram pod borer", "Semi-looper", "Aphid"],
          primaryDiseases: ["Wilt", "Ascochyta blight", "Rust"],
          riskLevel: "medium",
          ipmAdvice: [
            "Trichoderma seed treatment suppresses wilt in arid soils.",
            "Pheromone traps (10/ha) from flower initiation.",
            "Avoid sowing into moisture-logged pockets — collar rot strikes fast.",
          ],
          symptoms: [
            "Sudden wilting at flowering",
            "Grey-brown lesions on leaves and pods",
            "Frass around bored pods",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 25kg/acre at 30×10cm",
              "Trichoderma seed treatment",
              "Basal 10:20:20 NPK",
            ],
            "Sow into residual moisture within days of the last October rain — delays kill yield.",
          ],
          [
            "Vegetative Growth",
            45,
            "irrigation",
            [
              "Pre-flowering irrigation at 50 days",
              "Hoe and weed at 25 days",
              "Top-dress 20kg N at branching",
            ],
            "The pre-flowering water is gram's highest-return irrigation — never skip it.",
          ],
          [
            "Flowering & Pod Fill",
            40,
            "fertilization",
            [
              "Spray 0.2% boron at flowering",
              "Second irrigation at pod fill",
              "Weekly pod borer scouting",
            ],
            "Extend flowering with light moisture — more flower waves mean more pods.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Harvest at 80% pod yellowing",
              "Stack, sun-dry, thresh",
              "Bag clean for Lasalgaon",
            ],
            "Dry to 10% moisture — greenish seeds attract moisture discount at auction.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Rabi Onion (limited irrigation, var. Phule Samarth)",
        "Irrigated Cash Crop Option",
        "Where even a dug-well exists in arid Malegaon, Phule Samarth onion rides the March scarcity window at Pimpalgaon. Short-day, heat-tolerant bulbing makes it the one cash crop that converts limited water into premium onion rupees.",
        "Raise nursery in October; transplant 5 lakh seedlings/acre at 15×10cm by mid-November. Drip or furrow at 10–12 irrigations; stop 12 days before lifting.",
        "Nursery: October; transplanting: November",
        125,
        "Gram border rows; fenugreek inter-row",
        "8–12 t/acre of cured bulbs",
        "Pre-monsoon onion scarcity: ₹2,000–3,000/quintal for firm reds at Lasalgaon.",
        "Medium: 10–12 irrigations, drip preferred to stretch scarce water.",
        {
          yieldPotential: 75,
          marketValue: 90,
          waterEfficiency: 55,
          soilCompatibility: 78,
          climateResilience: 72,
        },
        { inputCostPerAcre: 32000, grossRevenuePerAcre: 70000, netProfitPerAcre: 38000 },
        wc(
          ["Nursery/Sowing", 55],
          ["Vegetative", 290],
          ["Flowering/Panicle", 240],
          ["Maturity/Harvest", 130],
        ),
        {
          primaryPests: ["Onion thrips", "Cutworm"],
          primaryDiseases: ["Purple blotch", "Basal rot"],
          riskLevel: "high",
          ipmAdvice: [
            "Blue sticky traps + threshold sprays for thrips in dry years.",
            "Rotate away from Alliums every 2 seasons.",
            "Cure fully — arid heat cures fast, protect from sunburn.",
          ],
          symptoms: [
            "Silvery streaking of leaf tips",
            "Sunken purple spots on leaves",
            "Soft base rot in warm damp pockets",
          ],
        },
        stages([
          [
            "Nursery & Transplanting",
            35,
            "sowing",
            [
              "Nursery October; 4kg seed/acre",
              "Transplant 5 lakh seedlings at 15×10cm",
              "Basal 25:50:50 NPK",
            ],
            "In arid belts, onion is an irrigation gamble — only commit where water is assured.",
          ],
          [
            "Vegetative Growth",
            55,
            "irrigation",
            [
              "Drip 8–10 L/m²/week",
              "Top-dress 25kg N at 45 days",
              "Two mechanical hoeings",
            ],
            "Stretch each litre — drip + mulch cuts arid evaporation by up to half.",
          ],
          [
            "Bulb Development",
            20,
            "fertilization",
            [
              "Potassium top-dress at bulb swell",
              "Withhold irrigation 12 days pre-lift",
              "Thrips threshold monitoring",
            ],
            "The moisture cut firms skin — firm skin is the arid-belt storage premium.",
          ],
          [
            "Maturity & Harvest",
            10,
            "harvest",
            [
              "Lift, cure in windrows 6–7 days",
              "Top and grade by diameter",
              "Dispatch to Pimpalgaon",
            ],
            "Grade hard by size — arid-zone onions compete on firmness, not size alone.",
          ],
        ]),
      ),
    ],
    summer: [
      makeCrop(
        "primary",
        "Summer Groundnut (var. TAG-24)",
        "Primary Recommended Crop",
        "On shallow arid soils with limited water, TAG-24 groundnut converts every irrigation into premium oilseed. Its short 105-day cycle fits the pre-monsoon window, and groundnut residues rebuild organic matter in the tired calcareous soils of Malegaon.",
        "Sow 60–70kg seed/acre at 30×10cm with gypsum 125kg/acre at flowering. Give 8–10 protective irrigations; stop 20 days before harvest for clean curing.",
        "February to mid-March",
        110,
        "Onion sequence; pigeon pea border",
        "900–1100 kg/acre of dry pods",
        "Groundnut ₹4,500–5,500/quintal at Dindori/Lasalgaon for bold milling grade.",
        "Medium: 8–10 irrigations; the most water-efficient high-value summer option.",
        {
          yieldPotential: 70,
          marketValue: 82,
          waterEfficiency: 58,
          soilCompatibility: 72,
          climateResilience: 75,
        },
        { inputCostPerAcre: 14000, grossRevenuePerAcre: 42000, netProfitPerAcre: 28000 },
        wc(
          ["Nursery/Sowing", 60],
          ["Vegetative", 220],
          ["Flowering/Panicle", 270],
          ["Maturity/Harvest", 90],
        ),
        {
          primaryPests: ["Tobacco caterpillar", "Leaf miner", "White grub"],
          primaryDiseases: ["Tikka leaf spot", "Rust", "Collar rot"],
          riskLevel: "medium",
          ipmAdvice: [
            "15-day mancozeb sprays from 45 days against tikka.",
            "Deep summer ploughing kills white grub.",
            "Seed dressing with thiram stops collar rot.",
          ],
          symptoms: [
            "Brown spots with yellow halo on leaves",
            "Orange pustules on leaf undersides",
            "Seedling collapse near soil line",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 60–70kg/acre at 30×10cm",
              "Basal 10:25:25 NPK",
              "Light irrigation to sprout",
            ],
            "Groundnut pegs into soil — keep the surface loose for easy peg penetration.",
          ],
          [
            "Vegetative Growth",
            40,
            "irrigation",
            [
              "Irrigate at 8-day intervals",
              "Two hoeings for aeration",
              "Start tikka sprays at 45 days",
            ],
            "Peanuts need well-aerated soil — avoid waterlogging in heavy pockets.",
          ],
          [
            "Flowering & Pegging",
            40,
            "fertilization",
            [
              "Gypsum 125kg/acre at flowering",
              "Spray 0.3% zinc twice",
              "Weekly Spodoptera scouting",
            ],
            "Gypsum's calcium fills pods — the best money you'll spend in groundnut.",
          ],
          [
            "Maturity & Harvest",
            18,
            "harvest",
            [
              "Lift at 75% dark testa",
              "Sun-dry 3–4 days on clean mat",
              "Winnow, grade, bag",
            ],
            "Test 10 pods — chocolate inner coat means lift now, not later.",
          ],
        ]),
      ),
      makeCrop(
        "secondary",
        "Bitter Gourd (var. Pusa Vishesh)",
        "Summer Vegetable Cash Crop",
        "Where drip water exists in arid Yeola, Pusa Vishesh bitter gourd capitalises on the hot summer vegetable scarcity. Its heat tolerance is elite, and Mumbai's year-round bitter-gourd appetite keeps prices firm through May.",
        "Sow 2 seeds/pit at 2.5×1m on drip beds; trellis at 6ft. Fertigate weekly with 19:19:19. Harvest fruit at 10–12cm every 3 days.",
        "March sowing; staggered second sowing in April",
        95,
        "Chilli inter-row; marigold border trap",
        "8–10 t/acre over 8–10 pickings",
        "Summer bitter gourd ₹15–25/kg at Nashik–Mumbai wholesale; scarcity-window pricing.",
        "Medium: drip 8–10 L/plant/day; drought-tolerant once established.",
        {
          yieldPotential: 78,
          marketValue: 76,
          waterEfficiency: 52,
          soilCompatibility: 65,
          climateResilience: 68,
        },
        { inputCostPerAcre: 18000, grossRevenuePerAcre: 45000, netProfitPerAcre: 27000 },
        wc(
          ["Nursery/Sowing", 40],
          ["Vegetative", 190],
          ["Flowering/Panicle", 230],
          ["Maturity/Harvest", 200],
        ),
        {
          primaryPests: ["Fruit fly", "Aphid", "Red pumpkin beetle"],
          primaryDiseases: ["Powdery mildew", "Downy mildew", "Mosaic"],
          riskLevel: "medium",
          ipmAdvice: [
            "Cue-lure traps (10/ha) for fruit fly — the main yield-killer.",
            "Early-morning azadirachtin sprays beat the pumpkin beetle.",
            "Rogue virus-diseased plants promptly.",
          ],
          symptoms: [
            "Sunken brown rot spots on young fruit",
            "White powdery coating in dry heat",
            "Mosaic yellowing and distortion",
          ],
        },
        stages([
          [
            "Sowing",
            12,
            "sowing",
            [
              "Sow 2 seeds/pit at 2.5×1m",
              "FYM + 20:40:40 in pits",
              "Install trellis early",
            ],
            "Trellis from day one — ground vines rot and fruit-fly damage multiplies.",
          ],
          [
            "Vegetative Growth",
            30,
            "irrigation",
            [
              "Drip 6–8 L/plant/day",
              "Pinch side shoots after 8th node",
              "Mulch for heat protection",
            ],
            "In 42°C heat, mulch under trellis cuts root-zone temperature 5–8°C.",
          ],
          [
            "Flowering & Fruit Set",
            30,
            "fertilization",
            [
              "Weekly fertigation 19:19:19",
              "Boron 0.2% at flowering",
              "Cue-lure trap servicing",
            ],
            "Female flowers dominate; hand-pollinate in heat waves to avoid drop.",
          ],
          [
            "Maturity & Harvest",
            23,
            "harvest",
            [
              "Pick at 10–12cm; every 3 days",
              "Cut with stalk; ventilated crates",
              "Overnight dispatch",
            ],
            "Pick young and regularly — every missed day shrinks the tender-fruit premium.",
          ],
        ]),
      ),
      makeCrop(
        "alternative",
        "Gingelly / Sesame (var. GT-1)",
        "Quick Drought-Hardy Oilseed",
        "GT-1 sesame matures in 80 days and thrives on meagre moisture — a perfect final crop before the monsoon rewets arid soils. Its golden seed earns premium oil-mill prices and it bolts before the peak heat curdles other crops.",
        "Sow 2.5kg seed/acre at 30×10cm after a light irrigation; 2–3 irrigations total. Harvest at 80% capsule dryness; thresh gently to avoid shattering.",
        "February to first week of March",
        82,
        "Groundnut sequence; pigeon pea border",
        "250–350 kg/acre of clean seed",
        "Til oil-mill price ₹11,000–14,000/quintal; fast local offtake at Malegaon.",
        "Low: 2–3 irrigations; near-drought hardy.",
        {
          yieldPotential: 55,
          marketValue: 85,
          waterEfficiency: 90,
          soilCompatibility: 70,
          climateResilience: 88,
        },
        { inputCostPerAcre: 5000, grossRevenuePerAcre: 18000, netProfitPerAcre: 13000 },
        wc(
          ["Nursery/Sowing", 35],
          ["Vegetative", 140],
          ["Flowering/Panicle", 150],
          ["Maturity/Harvest", 50],
        ),
        {
          primaryPests: ["Leaf webber", "Gall fly", "Sucking pests"],
          primaryDiseases: ["Phyllody", "Alternaria blight", "Root rot"],
          riskLevel: "medium",
          ipmAdvice: [
            "Rogue phyllody-affected plants (green leaf-like capsules).",
            "Avoid over-irrigation that fans root rot.",
            "Yellow sticky traps for sucking-pest flare-ups.",
          ],
          symptoms: [
            "Capsules reverting to leafy green structures (phyllody)",
            "Webbed, skeletonised terminal leaves",
            "Dark leaf spots with concentric rings",
          ],
        },
        stages([
          [
            "Sowing",
            10,
            "sowing",
            [
              "Sow 2.5kg/acre at 30×10cm",
              "Basal 10:20:20 NPK",
              "Light irrigation to germinate",
            ],
            "Sesame germinates in thin moisture — avoid waterlogging that rots the tiny seed.",
          ],
          [
            "Vegetative Growth",
            30,
            "irrigation",
            [
              "Two irrigations at 10-day intervals",
              "Hoe and weed at 20 days",
              "Thin to 10–12 plants/metre",
            ],
            "Keep plants compact — lush growth flops and shatters capsules later.",
          ],
          [
            "Flowering & Capsule Fill",
            30,
            "fertilization",
            [
              "Spray 0.2% boron at flowering",
              "Third irrigation at capsule fill",
              "Weekly phyllody roguing",
            ],
            "Phyllody (aster yellows) shows at flowering — pull affected plants before it spreads.",
          ],
          [
            "Maturity & Harvest",
            12,
            "harvest",
            [
              "Harvest at 80% capsule dryness; early morning",
              "Bind and dry 2–3 days before threshing",
              "Thresh gently; clean seed for oil mill",
            ],
            "Thresh at first light when humidity seals capsules — daytime heat shatters the seed.",
          ],
        ]),
      ),
    ],
  },
};

export function getFallbackRecommendations(
  region: RegionKey,
  season: SeasonKey,
): CropRecommendation[] {
  const set = FALLBACK_CROPS[region]?.[season];
  if (!set || set.length === 0) {
    return [FALLBACK_CROPS.central.rabi[0], FALLBACK_CROPS.central.rabi[1], FALLBACK_CROPS.central.rabi[2]];
  }
  return set;
}